<html>
<head>
    <title>Course Network</title>
    <link rel="stylesheet" href="/assets/css/bootstrap.min.css">
    <link rel="stylesheet" href="/assets/css/bootstrap-grid.min.css">
    <link rel="stylesheet" href="/assets/css/bootstrap-reboot.min.css">
    <link rel="stylesheet" href="/assets/css/main-style.css">
    <script src="/assets/js/jquery.min.js"></script>
    <script src="/assets/js/bootstrap.min.js"></script>
    <script src="/assets/js/application.js"></script>
</head>
<body>
<div class="wrapper">
    <?php $this->layout('menu/guest'); ?>
    <?php //if ($_SESSION = null): ?>
    <?php echo $this->content; ?>
    <?php //else :?>
       <!--<div style="background-color: #014c8c;height:200px;width:200px;"><div> -->
    <?php //var_dump($_SESSION);?>
    <?php //endif;?>
    <?php $this->layout('footer'); ?>
</div>
</body>
</html>